env:
  global:
    - secure: 2lHii2P+L18K05gySvR8tF4urG5nIa2j+TBGtHDWV8UzotcdmajUHNPT/70usMG5VnZxBssTPPoDXcNwabdB8fBmQkoRJTFGnsHYcftWHlSS8aAw067BXF+h9s+xzJyk3YL8m2PVNxaHCxQHoyhjqj9+hKbcoegw3bh3+R06aGuhg8HdMnLGqpk1J1VviUhvqLi7RlEyGd80SpAG8HMrpHJF0jqE6Jf6H3246ZAyw2L0SZ405sTZUgjKGqm/TI8Ckv7iQT9E/pJERsjiGx724jdoNSz0IvosCOzC4irEHryOVo+SBfO8hHcMCfk6ygT4JfTVrO4i0R+pGeLSn6+hkHtaR/Z9+7PC97e1bGDDkkcvYYjQzuxI/Rg1D3n2FMbE6mWMZ65v6VqoFpaS0zf/VLYvGcwy9XzDyP6zfewgl8wCdCIEV+e3Q3mTJqejNMDu4773JjRmAQAeNnNV3wPgpSexC5QbjxGekKjgzxhTI+4CZigd5gPTkMYIIS+Oba/mORriXBfNKesdROwYnFoS7D4gwUtfiQdn8orlPc2fTvy95hqbCO2V38SgJ/gbJAobOaGke1ZTWLjYumLlUf4nwXJvbiH8gvWOgsDLScmTF/3WriRXj6lbVyiQKd121XoSHolNCEEEt3a2FpIXRVWMoS5dXABgwFw1Jpl6+ydlwas=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_3
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
