env:
  global:
    - secure: KBRYwrfgEEZGA5iqZyXHzHi+BaYkfyn1D9kBAEjeS8PN+WsP4h+NOPh0BWUsPeF0kTzzzURsBH0tcsTgP6IpdHEw6ld7bYA4ZKG34cJFMeVncbGJKSfPOQDWn0kZkoB87B+/qsVi4HrsgqVqu1+PsQOCNvdyoq/1yth0Ft7yn66GAxcMKzFf3IRL+d1F2oC0VwqiyxD1qOE9w8WnL9qxzLPPaLRwT4/+1StOlLe8XehflQrfBpvtvDdCTKpz4cSgnpZLX55XQniF87XGp8HuQyOc1POFRkXlIuoG5oT+j9slBwSjhKZdQFZTrUsIhCogjH4wrYC9ZGK0BAAip22M41FjL/wC9EnkmmoDaD2C+vKfoVDssJapQw4dz/M4K/3loGZxcEiTRuki8PKLQFgMH0YQITjrUTXcilf/h6DXtpQtFopakF7Ki9SB2QjEHzIwLrfChQf3eGr9R2eQaLs3kOqj7Rz5lPJB1qt2LarKLOnWV24lOAsxDpuA650ERXqju50rrJkHnA8lF+mL2rGnWB64NpWMp8OEmQPVlwdGoCAQhzJ4oec8vEdjx93hYcfk3VEtH1wzLCnQIbh15rzpbM2458u+OLS20qOSgJFf0uos3zrdAn2FXwAVQ6VEdtuGVFuJbyS4Bnk8Z3/DK0BwsDtjZOCnwYjmBslGG76iyUU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BadIPs.com_Level_3
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
